# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-SourceForge
version:      0.082
version_from: 
installdirs:  site
requires:
    HTML::TableExtract:            0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
